<?php

/*
 * Created by tpay.com
 */
?>
<link rel="stylesheet" type="text/css" href="<?php echo $data['static_files_url'] ?>View/Styles/style.css"/>

<center>
    <div id="groups_v">
        <select name="bank_list" id="tpay-bank-list" onchange="changeBank()"></select>
    </div>
</center>
<?php echo $data['form'] ?>
<script>
    var s = document.createElement('script'),
        regulations_form_input = document.getElementById('tpay-regulations-input'),
        regulation_checkbox = document.getElementById('tpay-accept-regulations-checkbox'),
        changeBank = function () {
            document.getElementById('tpay-channel-input').value = document.getElementById('tpay-bank-list').value;
        };
    s.src = 'https://secure.tpay.com/groups-<?php echo $data['merchant_id'] ?>1.js';
    s.onload = function () {
        var str = '', i;
        for (i in tr_groups) {
            var group = tr_groups[i],
                id = group[0],
                name = group[1];
            str += '<option value="' + id + '" >' + name + '</option>';
        }
        document.getElementById('tpay-bank-list').innerHTML = str;
        changeBank();
    };
    document.getElementsByTagName('head')[0].appendChild(s);

    <?php if ($data['show_regulations_checkbox'] === true){ ?>

    regulation_checkbox.onchange = function () {
        regulations_form_input.value = (this.checked) ? 1 : 0;
    };

    <?php } ?>

</script>
